name: Publish Docker image

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub / GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push dev image
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          tags: |
            ghcr.io/murphycj/compass:dev
      - name: Push release image
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          tags: |
            ghcr.io/murphycj/compass:${{ github.event.release.tag_name }}
            ghcr.io/murphycj/compass:latest
